name: Platform Liberty Theme Project Setup
on: [repository_dispatch]
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
          with:
            persist-credentials: false
        - uses: sanity-io/github-action-sanity@v0.1-alpha
          env:
            repo_name: ${{ github.event.repository.name }}
            SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
          with: 
            args: init -y --create-project ${{env.repo_name}} --dataset dbset --output-path temp
        - name: Set env
          run: |
               echo ::set-env name=PROJECT_ID::$(echo PROJECT_ID | jq .api.projectId temp/sanity.json)
               echo ::set-env name=DATASET::$(echo DATASET | jq .api.dataset temp/sanity.json)
               echo ::set-env name=PROJECT_NAME::$(echo PROJECT_NAME | jq .project.name temp/sanity.json)
        - name: Test
          run: |
               sed -i -e 's/"PROJECT_ID"/'$PROJECT_ID'/g' studio/sanity.json
               sed -i -e 's/"DATASET_ID"/'$DATASET'/g' studio/sanity.json
               sed -i -e 's/"PROJECT_NAME"/'$PROJECT_NAME'/g' studio/sanity.json
               sed -i -e 's/"PROJECT_ID"/'$PROJECT_ID'/g' web/.env.production
               sed -i -e 's/"DATASET_ID"/'$DATASET'/g' web/.env.production
               sudo rm -r temp
               sudo rm -r studio/production.tar.gz
               sudo rm -r studio/node_modules
               sudo rm -r .github/workflows/provision.yml
        - name: Remote Add
          run:  git remote add blog https://github.com/VarshaKulkarni83/test-my-blog.git
        - name: Git-fetch-all
          run: git fetch --all
        - name: Git-checkout-origin
          run: git checkout -b sync-master blog/master
        - name: set user
          run: |
               git config --global user.email "platform-services@gmail.com"
               git config --global user.name "liberty"
        - name: Git-merge
          run: |
              git merge -Xtheirs master --allow-unrelated-histories
              git fetch --unshallow origin
              ls -al
        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
               github_token: 4eeec05997d6ba9fbe2b59ed1cb86a9739dc5a36
               repository: VarshaKulkarni83/test-my-blog
